# Generated by Django 3.2.3 on 2021-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='usertype',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Administrator', max_length=30),
        ),
    ]
