# Generated by Django 3.2.3 on 2021-06-06 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210605_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='item_buy',
            field=models.ManyToManyField(to='account.OrderItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('horror', 'horror'), ('thriller', 'thriller'), ('romance', 'romance'), ('supernatural', 'supernatural'), ('action', 'action')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=False, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=False, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
