# Generated by Django 3.2.3 on 2021-06-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210606_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_buy',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.order'),
        ),
    ]
