# Generated by Django 3.2.3 on 2021-06-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210606_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='ebooks',
            field=models.ManyToManyField(blank=True, to='account.Product'),
        ),
    ]
